# Define los servicios que componen la aplicación DiagnoVET

services:
  # --- 1. El Servicio de la Base de Datos PostgreSQL ---
  - type: pserv # Base de datos persistente
    name: diagnovet-db
    runtime: postgres
    # Plan gratuito. Los datos se borrarán después de 90 días de inactividad.
    plan: free 
    # Asegúrate de que la versión coincida con la que usaste localmente si es posible
    version: 14 

  # --- 2. El Servicio de la Aplicación Web con Flask ---
  - type: web
    name: diagnovet-app
    runtime: python
    plan: free # Plan gratuito para el servicio web
    # Comando para instalar las dependencias
    buildCommand: |
      pip install -r requirements.txt
      # Comando para crear las tablas de la BD en el primer despliegue
      flask shell -c "from app.models import db; db.create_all()"
    # Comando para iniciar la aplicación en producción con Gunicorn
    startCommand: "gunicorn run:app"
    envVars:
      # Variable de entorno para la URL de la base de datos
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: diagnovet-db
          property: connectionString
      # Variable para la clave de API de Gemini
      - key: GOOGLE_API_KEY
        sync: false # Le decimos a Render que la gestionaremos manualmente como un secreto