services:
  # --- 1. El Servicio de la Base de Datos PostgreSQL ---
  - type: pserv
    name: diagnovet-db
    plan: free # Plan gratuito. Los datos se borrarán tras 90 días de inactividad.

  # --- 2. El Servicio de la Aplicación Web con Flask ---
  - type: web
    name: diagnovet-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask shell -c "from app.models import db; db.create_all()"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: diagnovet-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false