services:
  - type: web
    name: diagnovet-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app.models import db; from run import app; app.app_context().push(); db.create_all()"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: diagnovet-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false

databases:
  - name: diagnovet-db
    plan: free